#include "Config.hpp"

namespace cfg {

int WINDOW_WIDTH = 970;
int WINDOW_HEIGHT = 720;
const char* WINDOW_TITLE = "Slot Machine";

int SLOTSVIEW_X = 50;
int SLOTSVIEW_Y = 50;
int SLOTSVIEW_HEIGHT = WINDOW_HEIGHT - SLOTSVIEW_Y * 2;
int SLOTSVIEW_WIDTH = SLOTSVIEW_HEIGHT;

int START_BUTTON_X = 720;
int START_BUTTON_Y = 50;
int START_BUTTON_WIDTH = 200;
int START_BUTTON_HEIGHT = 50;

int STOP_BUTTON_X = START_BUTTON_X;
int STOP_BUTTON_Y = START_BUTTON_Y + START_BUTTON_HEIGHT * 2;
int STOP_BUTTON_WIDTH = START_BUTTON_WIDTH;
int STOP_BUTTON_HEIGHT = START_BUTTON_HEIGHT;

int NUM_SLOT_ROWS = 5;
int NUM_SLOTS_IN_ROW = 25;

int START_SPIN_DURATION_MS = 1000;
int SPIN_MAX_DURATION_MS = 15000;
int STOP_MIN_DURATION_MS = 1000;
int SHOW_RESULTS_DURATION_MS = 3000;

float MIN_ROW_SPEED = 0.0002f;
float MAX_ROW_SPEED = 0.0005f;

const char* WIN_MESSAGE = "You won!";
const char* LOSE_MESSAGE = "You lost!";

}
